### ISSUE TITLE
[ПРЕДЛОЖЕНИЕ] Проверка Velocity (AntiKnockBack)

### ISSUE THREAD

**Issue by rejomy** [TestSender/HunterAntiCheat#1]
Мне очень понравилась проверка Velocity в AAC3 и я прошу Вас,добавить ее.
Это может быть как вариант, например просто teleportback, и добавлять вл. На видео всё видно.

Описание проверки:
Я прикреплю конфиг здесь, чтобы вы могли видеть что к чему: https://paste.md-5.net/yimicupise.bash
Я не знаю всей сути этой проверки, кода этой проверки у меня тоже нет, поэтому опишу только основной принцип. При ударе, если у игрока есть модификация отдачи, к ней добавляется VL заданный в конфиге, когда VL достигает предела, игрок начинает телепортироваться, за каждый телепорт тоже +vl, если VL достигает максимума, заданного в Actions, с игроком происходит какое-либо действие, кик, например.
Видео: https://youtu.be/OZtdU861JFk)

**Comment by TestSender** [comment]
Спасибо за предложение, в ближайшее время будет добавлено

**Comment by TestSender** [comment]
Звучит немного бредово, насчёт телепортации игрока, реализую возможно в другом ключе
